// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqIx2v0JBSV-9aKMaUfGHWsxXsT_rBja4',
    appId: '1:47799904669:web:33f57f5443f6b0464ea774',
    messagingSenderId: '47799904669',
    projectId: 'everybar-c6073',
    authDomain: 'everybar-c6073.firebaseapp.com',
    storageBucket: 'everybar-c6073.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvlB3n8xlARUdM_obtil1mhRCcEQuvXCo',
    appId: '1:47799904669:android:396771f5cff31a804ea774',
    messagingSenderId: '47799904669',
    projectId: 'everybar-c6073',
    storageBucket: 'everybar-c6073.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiG5kctoDE58zagH4z6_Op7k5QKGE0VAE',
    appId: '1:47799904669:ios:f74a8f277494e1c64ea774',
    messagingSenderId: '47799904669',
    projectId: 'everybar-c6073',
    storageBucket: 'everybar-c6073.appspot.com',
    iosClientId: '47799904669-lolc8hrs4eck55fjhpk2c3k3s9ittcme.apps.googleusercontent.com',
    iosBundleId: 'com.example.iBarApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiG5kctoDE58zagH4z6_Op7k5QKGE0VAE',
    appId: '1:47799904669:ios:2d09c0bb8d2ca4a84ea774',
    messagingSenderId: '47799904669',
    projectId: 'everybar-c6073',
    storageBucket: 'everybar-c6073.appspot.com',
    iosClientId: '47799904669-audg318gr6tm17crsqp5rno3ooup1bgp.apps.googleusercontent.com',
    iosBundleId: 'com.example.schoolInfoApp.RunnerTests',
  );
}
